version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: it_asset_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: it_asset_frontend
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: asset_nmd_gemini
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: it_asset_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html # Mount the built frontend files
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
